### ISSUE TITLE
Feature Request: /buy

### ISSUE THREAD

**Issue by mcastorina** [kilogram/autogm#13]
Easily purchase things by typing `/buy item_name [count] [unit price]`
This should add the item to the player's inventory and subtract the appropriate amount of gold.

**Comment by sidrdesai** [comment]
There should be a DM (direct message) sent to the DM (dungeon master) with a button to approve the transaction.

**Comment by kilogram** [comment]
*This* is dependent on the app owning character data, and in fact on it understanding relationships between players (this player is in this game which is GM'd by this user). The alternative is to statically define the GM, which is... fine I guess, but the app still has to own character data;and write to the spreadsheet.

I'd rather not have this feature until we've migrated off the spreadsheet. Thoughts?

**Comment by mcastorina** [comment]
I agree it would be easier once we've migrated. The issue I see is the way we are using the spreadsheet we have no way to write to it. Because we sync periodically we could run into conflicts too.

I don't think it's an issue to statically define the GM. Alternatively we could put the GM slack handle in the spreadsheet to look up.

**Comment by kilogram** [comment]
We could put the spreadsheet syncing in-process with the server, but then a) we have to implement our own oauth token refresh, and b) it's more exploitable because a) and it's now in the same process.

A valid counterargument is that the account that would be compromised is a bot account with no write access to anything.

So I think it's just a question of where we want to put our time. I personally would rather work on the migration, but if you think this is worthwhile then we'll merge your PR.

**Comment by mcastorina** [comment]
It's best to do this after the migration.

**Comment by kilogram** [comment]
Won't Fix (Obsolete)
